{% set version = "3.1-1" %} 
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmaptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmaptools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmaptools/tmaptools_{{ version }}.tar.gz
  sha256: fd89cb0d7fb44e0a5dd5311fa3e75a729746bf2e8e158d5ec423e5963f1b542d

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-kernsmooth
    - r-rcolorbrewer
    - r-xml
    - r-classint
    - r-dichromat
    - r-lwgeom >=0.1_4
    - r-magrittr
    - r-raster >=2.7_15
    - r-sf >=0.9
    - r-stars >=0.4_0
    - r-units >=0.6_1
    - r-viridislite
  run:
    - r-base
    - r-kernsmooth
    - r-rcolorbrewer
    - r-xml
    - r-classint
    - r-dichromat
    - r-lwgeom >=0.1_4
    - r-magrittr
    - r-raster >=2.7_15
    - r-sf >=0.9
    - r-stars >=0.4_0
    - r-units >=0.6_1
    - r-viridislite

test:
  commands:
    - $R -e "library('tmaptools')"           # [not win]
    - "\"%R%\" -e \"library('tmaptools')\""  # [win]

about:
  home: https://github.com/mtennekes/tmaptools
  license: GPL-3.0-only
  summary: Set of tools for reading and processing spatial data. The aim is to supply the workflow to create thematic maps. This package also facilitates 'tmap', the package for visualizing thematic maps.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  doc_url: https://cran.r-project.org/web/packages/tmaptools/tmaptools.pdf
  dev_url: https://github.com/mtennekes/tmaptools

extra:
  recipe-maintainers:
    - conda-forge/r
    - agcopenhaver
    - oblute
    - tata17

# Package: tmaptools
# Type: Package
# Title: Thematic Map Tools
# Version: 3.0
# Authors@R: person("Martijn", "Tennekes", email = "mtennekes@gmail.com", role = c("aut", "cre"))
# Description: Set of tools for reading and processing spatial data. The aim is to supply the workflow to create thematic maps. This package also facilitates 'tmap', the package for visualizing thematic maps.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Date: 2020-03-30
# Depends: R (>= 3.0), methods
# Imports: sf (>= 0.9), lwgeom (>= 0.1-4), stars (>= 0.4-0), units (>= 0.6-1), grid, raster (>= 2.7-15), classInt, KernSmooth, magrittr, RColorBrewer, viridisLite, stats, dichromat, XML
# Suggests: tmap (>= 2.2), rmapshaper, osmdata, OpenStreetMap, png, shiny, shinyjs
# URL: https://github.com/mtennekes/tmaptools
# BugReports: https://github.com/mtennekes/tmaptools/issues
# RoxygenNote: 7.1.0
# NeedsCompilation: no
# Packaged: 2020-03-30 14:17:44 UTC; mtes
# Author: Martijn Tennekes [aut, cre]
# Maintainer: Martijn Tennekes <mtennekes@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-03-30 15:00:02 UTC
