{% set version = '2.0-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmaptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmaptools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmaptools/tmaptools_{{ version }}.tar.gz
  sha256: 04850dcd778a9c5ea79b2b78e458549eba8a5d461cba2e32bac0c483072315d9

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-kernsmooth
    - r-rcolorbrewer
    - r-xml
    - r-classint
    - r-dichromat
    - r-lwgeom >=0.1_4
    - r-magrittr
    - r-raster >=2.7_15
    - r-rgdal
    - r-rgeos
    - r-sf >=0.7_1
    - r-sp
    - r-units >=0.6_1
    - r-viridislite
  run:
    - r-base
    - r-kernsmooth
    - r-rcolorbrewer
    - r-xml
    - r-classint
    - r-dichromat
    - r-lwgeom >=0.1_4
    - r-magrittr
    - r-raster >=2.7_15
    - r-rgdal
    - r-rgeos
    - r-sf >=0.7_1
    - r-sp
    - r-units >=0.6_1
    - r-viridislite

test:
  commands:
    - $R -e "library('tmaptools')"           # [not win]
    - "\"%R%\" -e \"library('tmaptools')\""  # [win]

about:
  home: https://github.com/mtennekes/tmaptools
  license: GPL-3
  summary: Set of tools for reading and processing spatial data. The aim is to supply the workflow
    to create thematic maps. This package also facilitates 'tmap', the package for visualizing
    thematic maps.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  doc_url: https://cran.r-project.org/web/packages/tmaptools/tmaptools.pdf
  dev_url: https://github.com/mtennekes/tmaptools

extra:
  recipe-maintainers:
    - conda-forge/r
    - agcopenhaver
    - oblute
    - tata17
