appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: MajC+hQzGrsVMmKp+i0sjQlaZioAyCcpSmLYxdHBn3nY56PKw33FoSLMKjOvSjEMQ/aIZpOaOWOdy8qUlAXSvVtPgEJ1D7LMwphV7aEIwmPaRf02IxWvSC1iY0+f6oYVstPm4scN8ytWDjVDSCw+pjlZ5VoehOwdnnV6tZxESnYBDl1D4m3mlA+8iTPQVXpz0CEbWhX0ugOfTMbsS0Kll4K5zBK+eXb+VtdXSGu9lZ9Xn5OwjLQSMb0guU6XIj6HGvBMVjuXq0wtH+tUUFyDuzB2DiUgxDLWcKbJkSebYeS1nF9gghITKA0m9/hW3YIEMdyHwxcYzzX9L6GcU9VvkLTMNdDFXl0vOFPbX4Ur2UIpR9RwQoAIXZc3BDGcX2mLffeTKDAk6ZeyRQvEWyZz6QoMHn7dwD2Jb2AXitRhYvZgYs029Ao1poZbiFQR2MQjPjJhFwqHMvv7WIMV7KljKrvImOz6/lVrdJrC4xz0jo3aVrC3moXlJJe3j1hUbzIoyvHCI15F+IrVQTGAOur6MprJhC4+GiT3pOD3/o9djVj0ShMKtarAmGtlB7BaXyb+1A6uW9pG+JlEE3tHQjPgvxssk06aea5eH22BVDqTGIpOZN0ooowtt5U5INxzDXYrgOoOD6W+7aD5Y/x2aZPKTHFmOIkPv1xVorZg6ZiH+s8=}
bot:
  automerge: true
